services:
  adguardhome:
    container_name: rdns
    restart: unless-stopped
    image: adguard/adguardhome
    network_mode: host
    volumes:
      - /opt/piumverate/003/rdns/conf:/opt/adguardhome/conf
      - /opt/piumverate/003/rdns/work:/opt/adguardhome/work

  npm:
    container_name: rproxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' 
      - '443:443'
    volumes:
      - /opt/piumverate/003/rproxy/data:/data
      - /var/piumverate/003/rproxy/letsencrypt:/etc/letsencrypt
    networks:
      ipvlan513:
        ipv4_address: 10.2.1.2
      web:

  nginx:
    container_name: loadbalancer
    image: nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '8000:8000'
      - '8006:8006'
    volumes:
      - /opt/piumverate/003/loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/piumverate/003/loadbalancer/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      ipvlan513:
        ipv4_address: 10.2.1.3
      web:

networks:
  ipvlan513:
    external: true
  web:
    external: true