services:
    nginx:
        container_name: loadbalancer
        volumes:
            - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /opt/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

        image: nginx:latest
        networks:
          - web
networks:
  web:
    external: true